/** @type {import('tailwindcss').Config} */
import LineClamp from "@tailwindcss/line-clamp";

module.exports = {
    darkMode: "class",
    content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
    theme: {
        extend: {
            width: {
                "1p": "1%",
                "2p": "2%",
                "3p": "3%",
                "4p": "4%",
                "5p": "5%",
                "6p": "6%",
                "7p": "7%",
                "8p": "8%",
                "9p": "9%",
                "10p": "10%",
                "11p": "11%",
                "12p": "12%",
                "13p": "13%",
                "14p": "14%",
                "15p": "15%",
                "16p": "16%",
                "17p": "17%",
                "18p": "18%",
                "19p": "19%",
                "20p": "20%",
                "21p": "21%",
                "22p": "22%",
                "23p": "23%",
                "24p": "24%",
                "25p": "25%",
                "26p": "26%",
                "27p": "27%",
                "28p": "28%",
                "29p": "29%",
                "30p": "30%",
                "31p": "31%",
                "32p": "32%",
                "33p": "33%",
                "34p": "34%",
                "35p": "35%",
                "36p": "36%",
                "37p": "37%",
                "38p": "38%",
                "39p": "39%",
                "40p": "40%",
                "41p": "41%",
                "42p": "42%",
                "43p": "43%",
                "44p": "44%",
                "45p": "45%",
                "46p": "46%",
                "47p": "47%",
                "48p": "48%",
                "49p": "49%",
                "50p": "50%",
                "51p": "51%",
                "52p": "52%",
                "53p": "53%",
                "54p": "54%",
                "55p": "55%",
                "56p": "56%",
                "57p": "57%",
                "58p": "58%",
                "59p": "59%",
                "60p": "60%",
                "61p": "61%",
                "62p": "62%",
                "63p": "63%",
                "64p": "64%",
                "65p": "65%",
                "66p": "66%",
                "67p": "67%",
                "68p": "68%",
                "69p": "69%",
                "70p": "70%",
                "71p": "71%",
                "72p": "72%",
                "73p": "73%",
                "74p": "74%",
                "75p": "75%",
                "76p": "76%",
                "77p": "77%",
                "78p": "78%",
                "79p": "79%",
                "80p": "80%",
                "81p": "81%",
                "82p": "82%",
                "83p": "83%",
                "84p": "84%",
                "85p": "85%",
                "86p": "86%",
                "87p": "87%",
                "88p": "88%",
                "89p": "89%",
                "90p": "90%",
                "91p": "91%",
                "92p": "92%",
                "93p": "93%",
                "94p": "94%",
                "95p": "95%",
                "96p": "96%",
                "97p": "97%",
                "98p": "98%",
                "99p": "99%",
                "1/5": "20%",
                "4/5": "80%"
            },
            colors: {
                primary: "#1a4797",
                secondary: "#01ADFF"
            },
            boxShadow: {
                "3xl": "14px 17px 40px 4px",
                inset: "inset 0px 18px 22px",
                "dark-inset": "0px 4px 4px inset",
                medium: "rgba(0, 0, 0, 0.24) 0px 3px 8px"
            },
            shadow: {
                500: "rgba(112, 144, 176, 0.08)",
            },
            translate: {
                "1/5": "20%",
            },
            inset: {
                "1/5": "20%"
            },
            keyframes: {
                shaking: {
                    "0%": {transform: "rotate(0)"},
                    "3%": {transform: "rotate(-28deg)"},
                    "5%": {transform: "rotate(34deg)"},
                    "7%": {transform: "rotate(-32deg)"},
                    "9%": {transform: "rotate(30deg)"},
                    "11%": {transform: "rotate(-28deg)"},
                    "13%": {transform: "rotate(26deg)"},
                    "15%": {transform: "rotate(-24deg)"},
                    "17%": {transform: "rotate(22deg)"},
                    "19%": {transform: "rotate(-20deg)"},
                    "21%": {transform: "rotate(18deg)"},
                    "23%": {transform: "rotate(-16deg)"},
                    "25%": {transform: "rotate(14deg)"},
                    "27%": {transform: "rotate(-12deg)"},
                    "29%": {transform: "rotate(10deg)"},
                    "31%": {transform: "rotate(-8deg)"},
                    "33%": {transform: "rotate(6deg)"},
                    "35%": {transform: "rotate(-4deg)"},
                    "37%": {transform: "rotate(2deg)"},
                    "39%": {transform: "rotate(-1deg)"},
                    "41%": {transform: "rotate(1deg)"},
                    "43%": {transform: "rotate(0)"},
                    "100%": {transform: "rotate(0)"},
                }
            },
            animation: {
                shaking: "shaking 5s ease-in-out infinite",
            }
        },
        fontSize: {
            xs: ["0.75rem", {lineHeight: "1.25rem"}],
            sm: ["0.875rem", {lineHeight: "1.375rem"}],
            base: ["1rem", {lineHeight: "1.5rem"}],
            md: ["1.125rem", {lineHeight: "1.625rem"}],
            lg: ["1.25rem", {lineHeight: "1.75rem"}],
            xl: ["1.625rem", {lineHeight: "2.125rem"}],
            "1.5xl": ["2rem", {lineHeight: "2.5rem"}],
            "2xl": ["2.25rem", {lineHeight: "2.75rem"}],
            "3xl": ["3rem", {lineHeight: "3.5rem"}],
            "4xl": ["4rem", {lineHeight: "4.5rem"}],
            h1: ["2.5rem", {lineHeight: "3.625rem"}],
            h2: ["2rem", {lineHeight: "2.125rem"}],
            h3: ["1.625rem", {lineHeight: "2.125rem"}],
            h4: ["1.25rem", {lineHeight: "1.725rem"}],
        },
    },
    plugins: [LineClamp],
};
